//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEnvSubstGeneratorSpec) DeepCopyInto(out *ClusterEnvSubstGeneratorSpec) {
	*out = *in
	if in.KubernetesVersion != nil {
		in, out := &in.KubernetesVersion, &out.KubernetesVersion
		*out = new(string)
		**out = **in
	}
	if in.ControlPlaneMachines != nil {
		in, out := &in.ControlPlaneMachines, &out.ControlPlaneMachines
		*out = new(int)
		**out = **in
	}
	if in.WorkerMachines != nil {
		in, out := &in.WorkerMachines, &out.WorkerMachines
		*out = new(int)
		**out = **in
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(int)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(int)
		**out = **in
	}
	if in.Datastore != nil {
		in, out := &in.Datastore, &out.Datastore
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEnvSubstGeneratorSpec.
func (in *ClusterEnvSubstGeneratorSpec) DeepCopy() *ClusterEnvSubstGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterEnvSubstGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEnvVars) DeepCopyInto(out *ClusterEnvVars) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEnvVars.
func (in *ClusterEnvVars) DeepCopy() *ClusterEnvVars {
	if in == nil {
		return nil
	}
	out := new(ClusterEnvVars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvSubstGeneratorSpec) DeepCopyInto(out *EnvSubstGeneratorSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterEnvSubstGeneratorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvSubstGeneratorSpec.
func (in *EnvSubstGeneratorSpec) DeepCopy() *EnvSubstGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(EnvSubstGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVars) DeepCopyInto(out *EnvVars) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterEnvVars, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVars.
func (in *EnvVars) DeepCopy() *EnvVars {
	if in == nil {
		return nil
	}
	out := new(EnvVars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratorsSpec) DeepCopyInto(out *GeneratorsSpec) {
	*out = *in
	if in.EnvSubst != nil {
		in, out := &in.EnvSubst, &out.EnvSubst
		*out = new(EnvSubstGeneratorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratorsSpec.
func (in *GeneratorsSpec) DeepCopy() *GeneratorsSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimControlPlaneEndpoint) DeepCopyInto(out *VCSimControlPlaneEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimControlPlaneEndpoint.
func (in *VCSimControlPlaneEndpoint) DeepCopy() *VCSimControlPlaneEndpoint {
	if in == nil {
		return nil
	}
	out := new(VCSimControlPlaneEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCSimControlPlaneEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimControlPlaneEndpointClusterStatus) DeepCopyInto(out *VCSimControlPlaneEndpointClusterStatus) {
	*out = *in
	in.EnvSubst.DeepCopyInto(&out.EnvSubst)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimControlPlaneEndpointClusterStatus.
func (in *VCSimControlPlaneEndpointClusterStatus) DeepCopy() *VCSimControlPlaneEndpointClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VCSimControlPlaneEndpointClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimControlPlaneEndpointList) DeepCopyInto(out *VCSimControlPlaneEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VCSimControlPlaneEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimControlPlaneEndpointList.
func (in *VCSimControlPlaneEndpointList) DeepCopy() *VCSimControlPlaneEndpointList {
	if in == nil {
		return nil
	}
	out := new(VCSimControlPlaneEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCSimControlPlaneEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimControlPlaneEndpointSpec) DeepCopyInto(out *VCSimControlPlaneEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimControlPlaneEndpointSpec.
func (in *VCSimControlPlaneEndpointSpec) DeepCopy() *VCSimControlPlaneEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(VCSimControlPlaneEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimModelSpec) DeepCopyInto(out *VCSimModelSpec) {
	*out = *in
	if in.VSphereVersion != nil {
		in, out := &in.VSphereVersion, &out.VSphereVersion
		*out = new(string)
		**out = **in
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(int)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(int)
		**out = **in
	}
	if in.ClusterHost != nil {
		in, out := &in.ClusterHost, &out.ClusterHost
		*out = new(int)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(int)
		**out = **in
	}
	if in.Datastore != nil {
		in, out := &in.Datastore, &out.Datastore
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimModelSpec.
func (in *VCSimModelSpec) DeepCopy() *VCSimModelSpec {
	if in == nil {
		return nil
	}
	out := new(VCSimModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimServer) DeepCopyInto(out *VCSimServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimServer.
func (in *VCSimServer) DeepCopy() *VCSimServer {
	if in == nil {
		return nil
	}
	out := new(VCSimServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCSimServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimServerList) DeepCopyInto(out *VCSimServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VCSimServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimServerList.
func (in *VCSimServerList) DeepCopy() *VCSimServerList {
	if in == nil {
		return nil
	}
	out := new(VCSimServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCSimServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimServerSpec) DeepCopyInto(out *VCSimServerSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(VCSimModelSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Generators.DeepCopyInto(&out.Generators)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimServerSpec.
func (in *VCSimServerSpec) DeepCopy() *VCSimServerSpec {
	if in == nil {
		return nil
	}
	out := new(VCSimServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimServerStatus) DeepCopyInto(out *VCSimServerStatus) {
	*out = *in
	in.EnvSubst.DeepCopyInto(&out.EnvSubst)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimServerStatus.
func (in *VCSimServerStatus) DeepCopy() *VCSimServerStatus {
	if in == nil {
		return nil
	}
	out := new(VCSimServerStatus)
	in.DeepCopyInto(out)
	return out
}
