//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEnvSubstGeneratorSpec) DeepCopyInto(out *ClusterEnvSubstGeneratorSpec) {
	*out = *in
	if in.KubernetesVersion != nil {
		in, out := &in.KubernetesVersion, &out.KubernetesVersion
		*out = new(string)
		**out = **in
	}
	if in.ControlPlaneMachines != nil {
		in, out := &in.ControlPlaneMachines, &out.ControlPlaneMachines
		*out = new(int)
		**out = **in
	}
	if in.WorkerMachines != nil {
		in, out := &in.WorkerMachines, &out.WorkerMachines
		*out = new(int)
		**out = **in
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(int)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(int)
		**out = **in
	}
	if in.Datastore != nil {
		in, out := &in.Datastore, &out.Datastore
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEnvSubstGeneratorSpec.
func (in *ClusterEnvSubstGeneratorSpec) DeepCopy() *ClusterEnvSubstGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterEnvSubstGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterEnvVars) DeepCopyInto(out *ClusterEnvVars) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterEnvVars.
func (in *ClusterEnvVars) DeepCopy() *ClusterEnvVars {
	if in == nil {
		return nil
	}
	out := new(ClusterEnvVars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvSubstGeneratorSpec) DeepCopyInto(out *EnvSubstGeneratorSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterEnvSubstGeneratorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvSubstGeneratorSpec.
func (in *EnvSubstGeneratorSpec) DeepCopy() *EnvSubstGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(EnvSubstGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVars) DeepCopyInto(out *EnvVars) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterEnvVars, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVars.
func (in *EnvVars) DeepCopy() *EnvVars {
	if in == nil {
		return nil
	}
	out := new(EnvVars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeAPIServerEndpoint) DeepCopyInto(out *FakeAPIServerEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeAPIServerEndpoint.
func (in *FakeAPIServerEndpoint) DeepCopy() *FakeAPIServerEndpoint {
	if in == nil {
		return nil
	}
	out := new(FakeAPIServerEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeAPIServerEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeAPIServerEndpointList) DeepCopyInto(out *FakeAPIServerEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FakeAPIServerEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeAPIServerEndpointList.
func (in *FakeAPIServerEndpointList) DeepCopy() *FakeAPIServerEndpointList {
	if in == nil {
		return nil
	}
	out := new(FakeAPIServerEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeAPIServerEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeAPIServerEndpointSpec) DeepCopyInto(out *FakeAPIServerEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeAPIServerEndpointSpec.
func (in *FakeAPIServerEndpointSpec) DeepCopy() *FakeAPIServerEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(FakeAPIServerEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeAPIServerEndpointStatus) DeepCopyInto(out *FakeAPIServerEndpointStatus) {
	*out = *in
	in.EnvSubst.DeepCopyInto(&out.EnvSubst)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeAPIServerEndpointStatus.
func (in *FakeAPIServerEndpointStatus) DeepCopy() *FakeAPIServerEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(FakeAPIServerEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratorsSpec) DeepCopyInto(out *GeneratorsSpec) {
	*out = *in
	if in.EnvSubst != nil {
		in, out := &in.EnvSubst, &out.EnvSubst
		*out = new(EnvSubstGeneratorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratorsSpec.
func (in *GeneratorsSpec) DeepCopy() *GeneratorsSpec {
	if in == nil {
		return nil
	}
	out := new(GeneratorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCCenterSpec) DeepCopyInto(out *VCCenterSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(VCSimModelSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Generators.DeepCopyInto(&out.Generators)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCCenterSpec.
func (in *VCCenterSpec) DeepCopy() *VCCenterSpec {
	if in == nil {
		return nil
	}
	out := new(VCCenterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCSimModelSpec) DeepCopyInto(out *VCSimModelSpec) {
	*out = *in
	if in.VSphereVersion != nil {
		in, out := &in.VSphereVersion, &out.VSphereVersion
		*out = new(string)
		**out = **in
	}
	if in.Datacenter != nil {
		in, out := &in.Datacenter, &out.Datacenter
		*out = new(int)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(int)
		**out = **in
	}
	if in.ClusterHost != nil {
		in, out := &in.ClusterHost, &out.ClusterHost
		*out = new(int)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(int)
		**out = **in
	}
	if in.Datastore != nil {
		in, out := &in.Datastore, &out.Datastore
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCSimModelSpec.
func (in *VCSimModelSpec) DeepCopy() *VCSimModelSpec {
	if in == nil {
		return nil
	}
	out := new(VCSimModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCenter) DeepCopyInto(out *VCenter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCenter.
func (in *VCenter) DeepCopy() *VCenter {
	if in == nil {
		return nil
	}
	out := new(VCenter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCenter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCenterList) DeepCopyInto(out *VCenterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VCenter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCenterList.
func (in *VCenterList) DeepCopy() *VCenterList {
	if in == nil {
		return nil
	}
	out := new(VCenterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCenterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCenterStatus) DeepCopyInto(out *VCenterStatus) {
	*out = *in
	in.EnvSubst.DeepCopyInto(&out.EnvSubst)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCenterStatus.
func (in *VCenterStatus) DeepCopy() *VCenterStatus {
	if in == nil {
		return nil
	}
	out := new(VCenterStatus)
	in.DeepCopyInto(out)
	return out
}
